# ─── Imports ──────────────────────────────────────────────────────────────────
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from PIL import Image
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras
from keras.datasets import mnist
from sklearn.metrics import confusion_matrix
import streamlit as st

try:
    from streamlit_drawable_canvas import st_canvas
    CANVAS_AVAILABLE = True
except ImportError:
    CANVAS_AVAILABLE = False

# ─── Page Config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="MNIST Digit Classifier",
    page_icon="✍️",
    layout="wide",
)

# ─── Custom CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@700;800&display=swap');
    html, body, [class*="css"] { font-family: 'Syne', sans-serif; background-color: #0a0a0f; color: #e8e8f0; }
    .stApp { background-color: #0a0a0f; }
    h1, h2, h3 { font-family: 'Syne', sans-serif !important; letter-spacing: -1px; }
    .metric-card { background: #111118; border: 1px solid #2a2a3a; border-radius: 14px; padding: 20px 24px; text-align: center; }
    .metric-card h2 { font-size: 2.5rem; color: #00ffc8; text-shadow: 0 0 20px rgba(0,255,200,0.4); margin: 0; }
    .metric-card p { font-family: 'Space Mono', monospace; font-size: 0.7rem; letter-spacing: 2px; text-transform: uppercase; color: #6b6b80; margin: 4px 0 0; }
    .prediction-big { background: linear-gradient(135deg, #111118, #16161f); border: 2px solid #00ffc8; border-radius: 16px; padding: 32px; text-align: center; box-shadow: 0 0 40px rgba(0,255,200,0.1); }
    .prediction-big h1 { font-size: 6rem; color: #00ffc8; text-shadow: 0 0 40px rgba(0,255,200,0.6); margin: 0; line-height: 1; }
    .prediction-big p { font-family: 'Space Mono', monospace; font-size: 0.75rem; letter-spacing: 3px; text-transform: uppercase; color: #6b6b80; margin-top: 8px; }
    .section-label { font-family: 'Space Mono', monospace; font-size: 0.65rem; letter-spacing: 3px; text-transform: uppercase; color: #6b6b80; border-bottom: 1px solid #2a2a3a; padding-bottom: 8px; margin-bottom: 16px; }
    div[data-testid="stButton"] button { background: linear-gradient(135deg, #7c3aed, #00ffc8) !important; color: #000 !important; font-family: 'Syne', sans-serif !important; font-weight: 700 !important; border: none !important; border-radius: 10px !important; padding: 10px 24px !important; }
    .stProgress > div > div { background: linear-gradient(90deg, #7c3aed, #00ffc8); border-radius: 4px; }
    .stTabs [data-baseweb="tab-list"] { background: #111118; border-radius: 10px; gap: 4px; }
    .stTabs [data-baseweb="tab"] { font-family: 'Space Mono', monospace; font-size: 0.75rem; letter-spacing: 1px; color: #6b6b80; border-radius: 8px; }
    .stTabs [aria-selected="true"] { background: #16161f !important; color: #00ffc8 !important; }
    .stAlert { border-radius: 10px; }
</style>
""", unsafe_allow_html=True)

# ─── Session State ─────────────────────────────────────────────────────────────
if "model"         not in st.session_state: st.session_state.model         = None
if "trained"       not in st.session_state: st.session_state.trained       = False
if "test_accuracy" not in st.session_state: st.session_state.test_accuracy = None
if "conf_mat"      not in st.session_state: st.session_state.conf_mat      = None
if "history"       not in st.session_state: st.session_state.history       = None
if "X_test"        not in st.session_state: st.session_state.X_test        = None
if "Y_test"        not in st.session_state: st.session_state.Y_test        = None

# ─── Auto-load saved model (generated by mnist_dc.py) ─────────────────────────
if not st.session_state.trained and os.path.exists("mnist_model.keras"):
    with st.spinner("Loading saved model from mnist_model.keras ..."):
        st.session_state.model = keras.models.load_model("mnist_model.keras")
        (_, _), (X_test, Y_test) = mnist.load_data()
        st.session_state.X_test = X_test / 255.0
        st.session_state.Y_test = Y_test
        Y_pred        = st.session_state.model.predict(st.session_state.X_test, verbose=0)
        Y_pred_labels = np.argmax(Y_pred, axis=1)
        st.session_state.conf_mat      = confusion_matrix(Y_test, Y_pred_labels)
        _, acc = st.session_state.model.evaluate(st.session_state.X_test, Y_test, verbose=0)
        st.session_state.test_accuracy = acc
        st.session_state.trained       = True

# ─── Header ───────────────────────────────────────────────────────────────────
st.markdown("""
<div style="margin-bottom:40px; padding-bottom:24px; border-bottom:1px solid #2a2a3a;">
    <h1 style="font-size:3rem; font-weight:800; letter-spacing:-2px; margin:0; line-height:1;">
        Neural <span style="color:#00ffc8; text-shadow:0 0 30px rgba(0,255,200,0.5);">Digit</span> Recogniser
    </h1>
    <p style="font-family:'Space Mono',monospace; font-size:0.7rem; color:#6b6b80; letter-spacing:2px; text-transform:uppercase; margin-top:6px;">
        MNIST · 60,000 Training Samples · Dense Neural Network
    </p>
</div>
""", unsafe_allow_html=True)

if st.session_state.trained:
    st.success(f"✅ Model ready — Test Accuracy: **{st.session_state.test_accuracy*100:.2f}%**")

# ─── Tabs ─────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["🧠  Train Model", "✍️  Predict Digit", "📊  Analytics"])


# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — TRAIN
# ══════════════════════════════════════════════════════════════════════════════
with tab1:
    if st.session_state.trained:
        st.info("✅ A trained model is already loaded. You can retrain below with different settings if you want.")

    st.markdown("<div class='section-label'>Model Configuration</div>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)
    with col1:
        epochs = st.slider("Epochs", 1, 30, 10)
    with col2:
        hidden_units = st.slider("Hidden Units (per layer)", 16, 256, 50, step=16)
    with col3:
        lr_map   = {"0.001 (Adam default)": 0.001, "0.0005": 0.0005, "0.01": 0.01}
        lr_label = st.selectbox("Learning Rate", list(lr_map.keys()))
        learning_rate = lr_map[lr_label]

    st.markdown("<br>", unsafe_allow_html=True)

    if st.button("⚡  Train Neural Network", use_container_width=True):
        with st.spinner("Loading MNIST dataset..."):
            (X_train, Y_train), (X_test, Y_test) = mnist.load_data()
            X_train = X_train / 255.0
            X_test  = X_test  / 255.0

        st.markdown("<div class='section-label'>Training Progress</div>", unsafe_allow_html=True)
        progress_bar = st.progress(0)
        epoch_text   = st.empty()

        model = keras.Sequential([
            keras.layers.Flatten(input_shape=(28, 28)),
            keras.layers.Dense(hidden_units, activation='relu'),
            keras.layers.Dense(hidden_units, activation='relu'),
            keras.layers.Dense(10, activation='softmax')
        ])
        model.compile(
            optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
        )

        acc_list, loss_list = [], []

        class StreamlitCallback(keras.callbacks.Callback):
            def on_epoch_end(self, epoch, logs=None):
                pct = int((epoch + 1) / epochs * 100)
                progress_bar.progress(pct)
                acc_list.append(logs.get('accuracy', 0))
                loss_list.append(logs.get('loss', 0))
                epoch_text.markdown(
                    f"<p style='font-family:Space Mono,monospace;font-size:0.8rem;color:#00ffc8;'>"
                    f"Epoch {epoch+1}/{epochs} — Acc: {logs.get('accuracy',0):.4f} — Loss: {logs.get('loss',0):.4f}</p>",
                    unsafe_allow_html=True
                )

        model.fit(X_train, Y_train, epochs=epochs, verbose=0, callbacks=[StreamlitCallback()])

        loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)
        Y_pred         = model.predict(X_test, verbose=0)
        Y_pred_labels  = np.argmax(Y_pred, axis=1)
        conf_mat       = confusion_matrix(Y_test, Y_pred_labels)

        # Save model — same as mnist_dc.py does
        model.save("mnist_model.keras")

        st.session_state.model         = model
        st.session_state.trained       = True
        st.session_state.test_accuracy = accuracy
        st.session_state.conf_mat      = conf_mat
        st.session_state.history       = {"acc": acc_list, "loss": loss_list}
        st.session_state.X_test        = X_test
        st.session_state.Y_test        = Y_test

        epoch_text.empty()
        st.success(f"✅ Model trained and saved as **mnist_model.keras**!")

        m1, m2, m3 = st.columns(3)
        with m1:
            st.markdown(f"<div class='metric-card'><h2>{accuracy*100:.2f}%</h2><p>Test Accuracy</p></div>", unsafe_allow_html=True)
        with m2:
            st.markdown(f"<div class='metric-card'><h2>{epochs}</h2><p>Epochs</p></div>", unsafe_allow_html=True)
        with m3:
            st.markdown(f"<div class='metric-card'><h2>{hidden_units}</h2><p>Units / Layer</p></div>", unsafe_allow_html=True)

        st.markdown("<br><div class='section-label'>Training Curves</div>", unsafe_allow_html=True)
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))
        fig.patch.set_facecolor('#0a0a0f')
        for ax in axes:
            ax.set_facecolor('#111118')
            ax.spines[['top','right','left','bottom']].set_color('#2a2a3a')
            ax.tick_params(colors='#6b6b80', labelsize=9)
        axes[0].plot(range(1, epochs+1), acc_list, color='#00ffc8', linewidth=2, marker='o', markersize=4)
        axes[0].set_title('Accuracy', color='#e8e8f0', fontsize=11, pad=10)
        axes[0].set_xlabel('Epoch', color='#6b6b80', fontsize=9)
        axes[0].fill_between(range(1, epochs+1), acc_list, alpha=0.1, color='#00ffc8')
        axes[1].plot(range(1, epochs+1), loss_list, color='#f59e0b', linewidth=2, marker='o', markersize=4)
        axes[1].set_title('Loss', color='#e8e8f0', fontsize=11, pad=10)
        axes[1].set_xlabel('Epoch', color='#6b6b80', fontsize=9)
        axes[1].fill_between(range(1, epochs+1), loss_list, alpha=0.1, color='#f59e0b')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    elif not st.session_state.trained:
        st.info("Configure the model above and click **Train Neural Network** to begin.")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — PREDICT
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    if not st.session_state.trained:
        st.warning("⚠️ Please train the model first (or make sure **mnist_model.keras** exists in the same folder).")
    else:
        st.markdown("<div class='section-label'>Input Method</div>", unsafe_allow_html=True)

        if CANVAS_AVAILABLE:
            input_mode = st.radio("", ["🖊️ Draw a digit", "📁 Upload an image"], horizontal=True, label_visibility="collapsed")
        else:
            input_mode = "📁 Upload an image"
            st.info("💡 Tip: Run `pip install streamlit-drawable-canvas` to also draw digits directly in the browser.")

        col_input, col_result = st.columns([1, 1], gap="large")

        with col_input:
            if input_mode == "🖊️ Draw a digit":
                st.markdown("<div class='section-label'>Draw below (white on black)</div>", unsafe_allow_html=True)
                canvas_result = st_canvas(
                    fill_color="rgba(255,255,255,1)",
                    stroke_width=18,
                    stroke_color="#ffffff",
                    background_color="#000000",
                    height=280, width=280,
                    drawing_mode="freedraw",
                    key="canvas",
                )
                if st.button("🔍  Predict Drawn Digit", use_container_width=True):
                    if canvas_result is not None and canvas_result.image_data is not None:
                        img_array  = canvas_result.image_data[:, :, :3]
                        gray       = cv2.cvtColor(img_array.astype(np.uint8), cv2.COLOR_RGB2GRAY)
                        resized    = cv2.resize(gray, (28, 28))
                        normalized = resized / 255.0
                        shaped     = np.reshape(normalized, [1, 28, 28])
                        pred       = st.session_state.model.predict(shaped, verbose=0)
                        st.session_state.last_pred       = int(np.argmax(pred))
                        st.session_state.last_conf       = float(np.max(pred))
                        st.session_state.last_pred_probs = pred[0]

            else:
                st.markdown("<div class='section-label'>Upload Image</div>", unsafe_allow_html=True)
                uploaded = st.file_uploader("", type=["png", "jpg", "jpeg", "bmp"], label_visibility="collapsed")

                if uploaded:
                    file_bytes = np.asarray(bytearray(uploaded.read()), dtype=np.uint8)
                    img_cv     = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
                    gray       = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
                    resized    = cv2.resize(gray, (28, 28))
                    normalized = resized / 255.0
                    shaped     = np.reshape(normalized, [1, 28, 28])
                    st.image(uploaded, caption="Uploaded Image", width=280)

                    if st.button("🔍  Predict Uploaded Digit", use_container_width=True):
                        pred = st.session_state.model.predict(shaped, verbose=0)
                        st.session_state.last_pred       = int(np.argmax(pred))
                        st.session_state.last_conf       = float(np.max(pred))
                        st.session_state.last_pred_probs = pred[0]

        with col_result:
            st.markdown("<div class='section-label'>Prediction Result</div>", unsafe_allow_html=True)
            if "last_pred" in st.session_state:
                pred_label = st.session_state.last_pred
                confidence = st.session_state.last_conf
                probs      = st.session_state.last_pred_probs

                st.markdown(f"""
                <div class='prediction-big'>
                    <h1>{pred_label}</h1>
                    <p>Recognised Digit</p>
                </div>
                """, unsafe_allow_html=True)

                st.markdown(f"<br><p style='font-family:Space Mono,monospace;font-size:0.8rem;color:#6b6b80;'>Confidence: <span style='color:#00ffc8;'>{confidence*100:.1f}%</span></p>", unsafe_allow_html=True)
                st.progress(confidence)

                st.markdown("<br><div class='section-label'>Class Probabilities</div>", unsafe_allow_html=True)
                fig, ax = plt.subplots(figsize=(6, 3))
                fig.patch.set_facecolor('#0a0a0f')
                ax.set_facecolor('#111118')
                colors = ['#00ffc8' if i == pred_label else '#2a2a3a' for i in range(10)]
                ax.bar(range(10), probs, color=colors, edgecolor='#16161f', linewidth=0.5)
                ax.set_xticks(range(10))
                ax.set_xticklabels([str(i) for i in range(10)], color='#6b6b80', fontsize=10)
                ax.set_ylim(0, 1)
                ax.spines[['top','right','left','bottom']].set_color('#2a2a3a')
                ax.tick_params(axis='y', colors='#6b6b80', labelsize=8)
                plt.tight_layout()
                st.pyplot(fig)
                plt.close()
            else:
                st.markdown("""
                <div style='background:#111118; border:1px dashed #2a2a3a; border-radius:14px; padding:48px; text-align:center;'>
                    <p style='font-family:Space Mono,monospace; font-size:0.75rem; color:#6b6b80; letter-spacing:2px;'>AWAITING INPUT</p>
                </div>
                """, unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — ANALYTICS
# ══════════════════════════════════════════════════════════════════════════════
with tab3:
    if not st.session_state.trained:
        st.warning("⚠️ Please train the model first.")
    else:
        conf_mat = st.session_state.conf_mat

        st.markdown("<div class='section-label'>Confusion Matrix</div>", unsafe_allow_html=True)
        fig, ax = plt.subplots(figsize=(10, 8))
        fig.patch.set_facecolor('#0a0a0f')
        ax.set_facecolor('#0a0a0f')
        sns.heatmap(conf_mat, annot=True, fmt='d', ax=ax,
                    cmap=sns.color_palette("light:#00ffc8", as_cmap=True),
                    linewidths=0.5, linecolor='#111118',
                    annot_kws={"size": 9, "color": "#0a0a0f", "fontfamily": "monospace"})
        ax.set_xlabel('Predicted Label', color='#6b6b80', fontsize=11, labelpad=10)
        ax.set_ylabel('True Label',      color='#6b6b80', fontsize=11, labelpad=10)
        ax.tick_params(colors='#6b6b80')
        ax.set_title('Confusion Matrix — Test Set', color='#e8e8f0', fontsize=13, pad=16)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        st.markdown("<br><div class='section-label'>Per-Class Accuracy</div>", unsafe_allow_html=True)
        per_class = conf_mat.diagonal() / conf_mat.sum(axis=1)
        fig2, ax2 = plt.subplots(figsize=(10, 3.5))
        fig2.patch.set_facecolor('#0a0a0f')
        ax2.set_facecolor('#111118')
        colors = ['#00ffc8' if v >= 0.97 else '#f59e0b' if v >= 0.93 else '#ff4d6d' for v in per_class]
        bars = ax2.bar(range(10), per_class * 100, color=colors, edgecolor='#0a0a0f', linewidth=0.5, width=0.65)
        ax2.set_xticks(range(10))
        ax2.set_xticklabels([f"Digit {i}" for i in range(10)], color='#6b6b80', fontsize=9)
        ax2.set_ylim(85, 101)
        ax2.set_ylabel('Accuracy (%)', color='#6b6b80', fontsize=9)
        ax2.spines[['top','right','left','bottom']].set_color('#2a2a3a')
        ax2.tick_params(axis='y', colors='#6b6b80', labelsize=8)
        for bar, val in zip(bars, per_class):
            ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.2,
                     f"{val*100:.1f}%", ha='center', va='bottom',
                     color='#e8e8f0', fontsize=8, fontfamily='monospace')
        plt.tight_layout()
        st.pyplot(fig2)
        plt.close()

        st.markdown("<br><div class='section-label'>Sample Test Images</div>", unsafe_allow_html=True)
        X_test = st.session_state.X_test
        Y_test = st.session_state.Y_test
        Y_pred = st.session_state.model.predict(X_test[:30], verbose=0)
        Y_pred_labels = np.argmax(Y_pred, axis=1)
        fig3, axes = plt.subplots(3, 10, figsize=(15, 5))
        fig3.patch.set_facecolor('#0a0a0f')
        for i, ax in enumerate(axes.flat):
            ax.imshow(X_test[i], cmap='gray')
            correct = Y_pred_labels[i] == Y_test[i]
            col = '#00ffc8' if correct else '#ff4d6d'
            ax.set_title(f"{Y_pred_labels[i]}", color=col, fontsize=8, fontfamily='monospace')
            ax.axis('off')
        plt.tight_layout()
        st.pyplot(fig3)
        plt.close()

# ─── Footer ───────────────────────────────────────────────────────────────────
st.markdown("""
<hr style="border-color:#2a2a3a; margin-top:48px;">
<p style="font-family:'Space Mono',monospace; font-size:0.65rem; color:#6b6b80; text-align:center; letter-spacing:2px; text-transform:uppercase; padding:16px 0;">
    MNIST Neural Digit Recogniser · Keras + TensorFlow · Streamlit UI
</p>
""", unsafe_allow_html=True)